### ISSUE TITLE
Support files and stdin

### ISSUE THREAD

**Issue by nihaals** [bottom-software-foundation/bottom-go#2]

**Comment by K1ngjulien** [comment]
This should be pretty easy by just using an `io.Reader` instead of a `string` as the argument, right?

**Comment by K1ngjulien** [comment]
@nihaals

I've been thinking about this. For file support, the easiest way would be to buffer the entire file and then convert it.

But a better way would be using `io.Reader` and `io.Writer` as the in and outputs of encode/decode. That would allow streaming data directly from `os.Stdin` to `os.Stdout` and using files as input and output is then also pretty simple.

"Unfortunately" the validation logic would have to happen during decoding and may stop half way through, tho i don' think that that should be much of an issue as people shouldnt be passing in invalid data anyway.

**Comment by K1ngjulien** [comment]
Additionaly it should be possible to implement an encoder as per https://pkg.go.dev/encoding which would definitely be the slickest implementation.

I don't have time to day but I wil look further into this tomorrow

**Comment by nihaals** [comment]
I think using streams would work well. I'm not sure how I want to handle string inputs, requiring something like `echo "Hello, world!" | bottom` might be annoying but I don't think assuming it's a string if it's not a valid file works well either. We could add a flag that toggles if a file or string is used but I think that's overkill. I guess the best solution would be to just force it to be a file and bundle it with #5 as v0.2.0. When/if the next version of the spec is released we can probably release v1.0.0 as most of the inconsistencies and ambiguities should be fixed.

**Comment by K1ngjulien** [comment]
I was thinking about something along these lines:

If args are supplied, use those by checking `flags.NArgs() > 0`:
```
$ bottom "hello"
$ bottom -d "<valid bottom>"
```

If files are supplied, use those:
```
$ bottom -i input.txt -o output.txt
$ bottom -d -i input.txt -o output.txt

// this would write the output to stdout and read the input from the file
$ bottom -i input.txt 

// this write the output to the file and read the input from stdin
$ bottom -o output.txt
```

And if none are supplied, read from stdin, and write to stdout
```
$ echo "hello" | bottom | less
$ echo "<some valid bottom>" | bottom -d | less
```

If there's some conflict, like an input string and an input file, we throw an error.


If encoder and decoder are defined as `io.Reader` and `io.Writer` this would make the glue code in main really easy:

```go
// encode string input and stdout
inputReader := strings.NewReader(f.Arg(0))
outputReader := bottom.NewEncoder(inputReader)
io.Copy(os.Stdout, outputReader)
```

```go
// decode file input to file output
inputFile, _ := os.Open("input.txt")
outputFile, _ := os.OpenFile("output.txt", os.O_WR|os.O_CREATE, 0755)
outputReader := bottom.NewDecoder(inputFile)
io.Copy(outputFile, outputReader)
```

What do you think?

**Comment by nihaals** [comment]
I like it a lot, it also mirrors familiar CLI tools.
I think we should also aim to support combined flags, e.g. `$ bottom -di input.txt` but as `flag` doesn't seem to do this by default it can be something in the future

**Comment by nihaals** [comment]
Some rough test cases:
```
💖💖,,,,👉👈... is truncated, the full expected result would be:
💖💖,,,,👉👈💖💖,👉👈💖💖🥺,,,👉👈💖💖🥺,,,👉👈💖💖✨,👉👈

$ bottom "hello"
💖💖,,,,👉👈...

$ bottom -d "💖💖,,,,👉👈..."
hello

$ echo "hello" > input.txt
$ bottom -i input.txt -o output.txt
$ cat output.txt
💖💖,,,,👉👈...

$ echo "💖💖,,,,👉👈..." > input.txt
$ bottom -d -i input.txt -o output.txt
$ cat output.txt
hello

$ echo "hello" > input.txt
$ bottom -i input.txt
💖💖,,,,👉👈...

$ echo "💖💖,,,,👉👈..." > input.txt
$ bottom -d -i input.txt
hello

$ echo "hello" | bottom
💖💖,,,,👉👈...

$ echo "💖💖,,,,👉👈..." | bottom -d
hello

$ echo "hello" | bottom -i input.txt
Error

$ echo "💖💖,,,,👉👈..." | bottom -d -i input.txt
Error

$ echo "hello" | bottom "hello"
Error

$ echo "hello" | bottom -i input.txt "hello"
Error

$ bottom -i input.txt "hello"
Error

$ echo "hello" > input.txt
$ echo "not hello" | bottom -i input.txt
💖💖,,,,👉👈...

$ rm input.txt
$ bottom -i input.txt
Error

$ bottom
Error
```

I think things like `bottom -di input.txt` and `bottom -i-` can be left out for now
