### ISSUE TITLE
UTF-8 encoding

### ISSUE THREAD

**Issue by K1ngjulien** [bottom-software-foundation/bottom-go#3]
Great stuff, but unless I'm missing something, this will only work with ASCII text.

https://github.com/bottom-software-foundation/bottom-go/blob/ffac14ba06961de1dec70b095d2fe14753389653/bottom/bottom.go#L26

The spec states that it should be able to encode any valid UTF-8 characters, in which case we'd have to loop over the runes and not the bytes in the string.

PS: Go supports UTF-8 in its source files, so you should be able to insert the emoji directly instead of their escape  sequences.

**Comment by nihaals** [comment]
> so you should be able to insert the emoji directly

I intentionally used escape sequences because inserting emoji into code feels weird to me

**Comment by nihaals** [comment]
```
$ go run cmd/main.go "🫂"
🫂✨✨✨✨👉👈💖💖💖🥺,,,,👉👈💖💖💖✨✨,👉👈💖💖✨✨✨👉👈
```
This looks like the expected output. Do you have an example?

**Comment by romdotdog** [comment]
This is not according to spec. It should be handling the bytes _after_ UTF-8 encoding, **not** the codepoints themselves. Unless I am missing something, there shouldn't be more than one 🫂 in each byte separator.

**Comment by nihaals** [comment]
This seems to be the same output bottom-web gives and it can also decode it fine

**Comment by romdotdog** [comment]
Apologies, upon copy pasting into a code editor, everything looks fine. Seems to be a browser rendering glitch.

**Comment by K1ngjulien** [comment]
Oh ok sorry, I misread the spec without trying it out 🥺👉👈

I tried out the kanji example from the `bottom-rs` readme and it gives the same result.
